version: "3"

services:
  mikubot:
    build: .
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - default

  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mikubot'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - default

networks:
  default:
