version: "3"

services:
  mikubot:
    build: .
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: 'mikubot'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'