version: "3"

services:
  mikubot:
    build: .
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
    - ./logs:/app/logs

  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'mikubot'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'

